AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'config/**/*'
    - '**/Gemfile'
    - '**/Rakefile'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'spec/factories/*'
    - 'bin/setup'
    - 'bin/update'

  SuggestExtensions: false

  DisplayCopNames: true

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Enabled: false

Lint/MissingCopEnableDirective:
  Enabled: false

Style/Documentation:
  Enabled: false
